"""collectors/api.py — API surface from OpenAPI YAML or Markdown tables.

Prefer a machine-readable OpenAPI file (`api.yaml` / `openapi.yaml`) when
present; fall back to README/docs Markdown method/path tables so existing
targets keep working.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

import yaml

_API_CANDIDATES = ("api.yaml", "openapi.yaml", "openapi.yml")

_ENDPOINT_ROW_RE = re.compile(
    r"^\|\s*`?(?P<method>GET|POST|PUT|PATCH|DELETE)`?\s*"
    r"\|\s*`?(?P<path>/[^`|]*?)`?\s*"
    r"\|(?P<description>[^|]*)\|?\s*$",
    re.IGNORECASE,
)

_PATH_PARAM_DEFAULTS = {
    "slug": None,
    "project": None,
    "sprint_label": "sprint-1",
    "issue_id": "1",
    "issue_num": "1",
    "path": "README.md",
}


def fill_path_params(path: str, target: str) -> str:
    filled = path
    for name, default in _PATH_PARAM_DEFAULTS.items():
        value = target if name in ("slug", "project") else default
        filled = filled.replace("{" + name + "}", str(value))
    filled = re.sub(r"\{[^}]+\}", "example", filled)
    return filled


def parse_endpoint_tables(text: str) -> list[dict]:
    """Extract GET endpoints from Markdown method/path tables."""
    seen: set[str] = set()
    endpoints: list[dict] = []
    for line in text.splitlines():
        m = _ENDPOINT_ROW_RE.match(line.strip())
        if not m:
            continue
        if m.group("method").upper() != "GET":
            continue
        path = m.group("path").strip()
        if not path.startswith("/") or path in seen:
            continue
        seen.add(path)
        endpoints.append({
            "path": path,
            "description": m.group("description").strip().strip("`"),
            "source": "readme-table",
        })
    return endpoints


def parse_openapi_yaml(text: str, source_label: str = "api.yaml") -> list[dict]:
    """Extract GET paths from an OpenAPI 3 document (paths + summary/description)."""
    try:
        data = yaml.safe_load(text) or {}
    except yaml.YAMLError:
        return []
    if not isinstance(data, dict):
        return []
    paths = data.get("paths") or {}
    if not isinstance(paths, dict):
        return []
    endpoints: list[dict] = []
    seen: set[str] = set()
    for path, methods in paths.items():
        if not isinstance(path, str) or not path.startswith("/"):
            continue
        if not isinstance(methods, dict):
            continue
        get = methods.get("get") or methods.get("GET")
        if not isinstance(get, dict):
            continue
        if path in seen:
            continue
        seen.add(path)
        desc = (
            get.get("summary")
            or get.get("description")
            or methods.get("summary")
            or ""
        )
        endpoints.append({
            "path": path,
            "description": str(desc).strip(),
            "source": source_label,
        })
    return endpoints


def find_openapi_file(local_path: Path) -> Path | None:
    for name in _API_CANDIDATES:
        p = local_path / name
        if p.is_file():
            return p
    return None


def endpoints_to_openapi(
    endpoints: list[dict],
    *,
    title: str,
    version: str = "0.1.0",
) -> dict:
    """Build a minimal OpenAPI 3 document from Lookout endpoint dicts."""
    paths: dict = {}
    for ep in endpoints:
        path = ep.get("path")
        if not path:
            continue
        paths[path] = {
            "get": {
                "summary": ep.get("description") or path,
                "responses": {
                    "200": {
                        "description": ep.get("response")
                        or (ep.get("description") or "OK"),
                    }
                },
            }
        }
    return {
        "openapi": "3.0.3",
        "info": {
            "title": title,
            "version": version,
            "description": (
                "Generated by Lookout from documented read surfaces. "
                "Promote into the target repo as api.yaml when ready."
            ),
        },
        "paths": paths,
    }


def collect_endpoints(local_path: Path, out_dir: Path, target: str = "") -> dict:
    """Write endpoints.json — OpenAPI first, Markdown tables as fallback."""
    try:
        endpoints: list[dict] = []
        source_files: list[str] = []
        name = target or local_path.name

        openapi = find_openapi_file(local_path)
        if openapi is not None:
            rel = str(openapi.relative_to(local_path))
            found = parse_openapi_yaml(
                openapi.read_text(encoding="utf-8", errors="replace"),
                source_label=rel,
            )
            for e in found:
                filled = fill_path_params(e["path"], name)
                e["example"] = f"curl -sS http://localhost:8000{filled}"
                desc = e.get("description") or "JSON body"
                e["response"] = f"200 JSON — {desc}"
            endpoints = found
            if found:
                source_files.append(rel)
        else:
            seen: set[str] = set()
            candidates = [local_path / "README.md"]
            docs_dir = local_path / "docs"
            if docs_dir.is_dir():
                candidates.extend(sorted(docs_dir.rglob("*.md")))
            for p in candidates:
                if not p.is_file():
                    continue
                found = parse_endpoint_tables(
                    p.read_text(encoding="utf-8", errors="replace")
                )
                fresh = [e for e in found if e["path"] not in seen]
                if not fresh:
                    continue
                rel = str(p.relative_to(local_path))
                for e in fresh:
                    seen.add(e["path"])
                    e["source"] = rel
                    filled = fill_path_params(e["path"], name)
                    e["example"] = f"curl -sS http://localhost:8000{filled}"
                    desc = e.get("description") or "JSON body"
                    e["response"] = f"200 JSON — {desc}"
                endpoints.extend(fresh)
                source_files.append(rel)

        (out_dir / "endpoints.json").write_text(
            json.dumps(
                {"get_endpoints": endpoints, "source_files": source_files},
                indent=2,
            )
            + "\n",
            encoding="utf-8",
        )
        return {
            "status": "ok" if endpoints else "absent",
            "error": "",
            "count": len(endpoints),
            "from_openapi": openapi is not None and bool(endpoints),
        }
    except Exception as exc:
        return {"status": "absent", "error": str(exc), "count": 0, "from_openapi": False}
